FROM iojs:onbuild

ENV HUBOT_PORT 8080
ENV HUBOT_ADAPTER slack
ENV HUBOT_NAME petalbot
ENV HUBOT_SLACK_TOKEN=xxxxxxxxxxxxxxxx
ENV HUBOT_SLACK_TEAM petalmd
ENV HUBOT_SLACK_BOTNAME ${HUBOT_NAME}
ENV PORT ${HUBOT_PORT}
#ENV HUBOT_LOG_LEVEL debug

ENV HUBOT_ASSEMBLA_API_APP_ID xxxxxxxxxxxxxxxx
ENV HUBOT_ASSEMBLA_API_APP_SECRET xxxxxxxxxxxxxxxx
ENV HUBOT_ASSEMBLA_SPACE petalmd

EXPOSE ${HUBOT_PORT}

CMD bin/hubot
